set nocompatible
syntax on
set bg=dark

set modelines=5
set modeline

inoremap jk <Esc>l
let mapleader = "\<Space>"

set hidden

nnoremap ' `
nnoremap ` '

set backspace=2
set laststatus=2

nnoremap ; :
set autowrite

set splitright


